<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width">
<link rel="stylesheet" href="/css/styles.css">
<script src="scripts/jquery.2.0.3.min.js"></script>
<script type="text/javascript" src="scripts/hide-password.min.js"></script>
<script type="text/javascript" src="scripts/common.js"></script>
<script type="text/javascript" src="scripts/jquery.cookie.js"></script>
